"""Generate RESEARCH.md from experiment database."""

import sqlite3


def generate_report(conn: sqlite3.Connection) -> str:
    experiments = conn.execute(
        "SELECT * FROM experiments ORDER BY started_at DESC"
    ).fetchall()

    if not experiments:
        return "# Experiment Log\n\nNo experiments recorded yet.\n"

    # Summary stats
    total = len(experiments)
    by_status = {}
    for exp in experiments:
        s = exp["status"]
        by_status[s] = by_status.get(s, 0) + 1

    # Best scores per eval
    bests = conn.execute(
        """SELECT eval_name, MAX(score) as best, experiment_id
           FROM evaluations
           JOIN experiments ON experiments.id = evaluations.experiment_id
           WHERE experiments.status = 'completed'
           GROUP BY eval_name"""
    ).fetchall()

    lines = ["# Experiment Log", "", "Generated by autoexp.", ""]

    # Summary
    lines.append("## Summary")
    lines.append(f"- **Total experiments:** {total}")
    status_parts = [f"{s}: {n}" for s, n in sorted(by_status.items())]
    lines.append(f"- **By status:** {' | '.join(status_parts)}")
    if bests:
        for b in bests:
            lines.append(f"- **Best {b['eval_name']}:** {b['best']} ({b['experiment_id']})")
    lines.append("")

    # Experiment table
    lines.append("## Experiments")
    lines.append("")
    lines.append("| ID | Hypothesis | Status | Duration | Evals |")
    lines.append("|----|-----------|--------|----------|-------|")

    for exp in experiments:
        exp_id = exp["id"]
        hypothesis = (exp["hypothesis"] or "")[:60]
        status = exp["status"]

        # Duration
        duration = ""
        if exp["started_at"] and exp["finished_at"]:
            from datetime import datetime

            try:
                start = datetime.fromisoformat(exp["started_at"])
                end = datetime.fromisoformat(exp["finished_at"])
                secs = (end - start).total_seconds()
                if secs > 3600:
                    duration = f"{secs / 3600:.1f}h"
                elif secs > 60:
                    duration = f"{secs / 60:.0f}m"
                else:
                    duration = f"{secs:.0f}s"
            except (ValueError, TypeError):
                pass

        # Eval scores
        evals = conn.execute(
            "SELECT eval_name, score FROM evaluations WHERE experiment_id = ?",
            (exp_id,),
        ).fetchall()
        eval_str = ", ".join(f"{e['eval_name']}={e['score']:.3f}" for e in evals) if evals else "-"

        lines.append(f"| {exp_id} | {hypothesis} | {status} | {duration} | {eval_str} |")

    lines.append("")
    return "\n".join(lines)
